### ISSUE TITLE
Crashing on opening Starpointe

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#1157] opened 2015-05-28 08:20 UTC
Source: https://openrct.net/forum/topic/42/starpointe-crashing-openrct

Hi, 

Im still pretty new to all this! So I just want to say, I LOVE OpenRCT!!!! It's really gotten me back into the game. 
I am having a problem when trying to load the park, Starpointe. 
I am receiving the following errors:

http://i.imgur.com/UCwKlaz.png
http://i.imgur.com/vEX4oyR.png

Im guessing this crash is from the Amazing Earl rides and whatever else is showing the CMD box?
If you haven't played Starpoint - I believe it may be one of the BEST RCT2 parks around. You can download the park from NE Designs here: http://www.nedesigns.com/park/2914/starpointe/
Thanks!
- Taylor

**Comment by duncanspumpkin** [comment] 2015-05-28 11:13
Is this yet another map that has abused 8cars and is causing a crash?

**Comment by Gymnasiast** [comment] 2015-05-28 11:51
Definitely. If you look at the screenshots, there are invisible ride entrances, invisible track pieces, wooden roller coaster tracks with monster truck tracks on the same level and a lot of zero clearance.

Still, if a SV6 loads correctly in RCT2, shouldn't OpenRCT2 be able to do the same (eventually)?

**Comment by duncanspumpkin** [comment] 2015-05-28 17:47
The problem is its accessing invalid memory. We can disable the checks buts its not really a safe way to run the game.

**Comment by IntelOrca** [comment] 2015-05-28 17:49
What is accessing invalid memory?

**Comment by duncanspumpkin** [comment] 2015-05-28 17:50
If its like the other ones i've looked into. During a check for station start it loops past the end of the map_element and keeps going until it finds anything that matches the requirements.

**Comment by IntelOrca** [comment] 2015-05-28 18:03
Is this un-reversed code? Otherwise we can add a fix for this.

**Comment by duncanspumpkin** [comment] 2015-05-28 18:13
Its reversed code. I'll just get the exact function call.

**Closed** 2015-05-28 20:33 UTC
