### ISSUE TITLE
Can't give in name when scenario completed

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#844] opened 2015-02-20 15:09 UTC
Is it normal that I can't fill in my name when I've completed a scenario?
https://www.dropbox.com/s/f9pmi29n7k75bua/Schermafdruk%202015-02-20%2016.07.57.png?dl=0
Fyi, it's a custom scenario. I don't know if that should show a name dialog or not.

**Comment by Gymnasiast** [comment] 2015-02-20 15:18
Seems a duplicate of #639 to me.

**Comment by runelaenen** [comment] 2015-02-20 15:20
I'm sorry I haven't seen your comment, I was however aware of the name not showing up in the list but I thought that had been fixed, looks like not :p

**Comment by IntelOrca** [comment] 2015-02-21 02:05
@runelaenen Could you try to see if there are still bugs with scenario name entering please. I have added a cheat to complete the scenario.

**Comment by Gymnasiast** [comment] 2015-02-21 08:53
The game now crashes when I win some scenarios. It doesn't matter whether I win it with or without the 'Win Scenario' cheat.
My console print the following message once it crashes:
```
VERBOSE: loading objwine: Unhandled exception 0xc0000417 in thread 9 at address 0x320023:0x10094222 (thread 0009), starting debugger...
```
I can't give a dump, since the crash window still says it's loading it (even though it should take about one second).

The scenarios I tried were Evergreen Gardens (I can supply both the SC6 and SV6) and several parks I downloaded from the internet. But it doesn't crash in _all_ of those. Furthermore, I tried several built-in scenarios, and those did work.

**Comment by IntelOrca** [comment] 2015-02-21 10:21
@Gymnasiast I tried some scenario I found of Evergreen Gardens and it worked for me. Could you send me your version please.

**Comment by Gymnasiast** [comment] 2015-02-21 14:18
Here a both the SC6 and SV6: http://drpil.nl/org/evergreen_gardens_win_crash.zip
Strangely though, when I open a new game from that SC6 and use the win cheat on that, it doesn't crash. It only crashes when winning the scenario from the SV6.

**Comment by IntelOrca** [comment] 2015-02-21 16:38
@Gymnasiast Ah I know why - I haven't set the scenario path variable when loading a game.

**Comment by ThomasdenH** [comment] 2015-02-22 16:54
I'm not sure if it is related, but I finished a scenario and it did register it, but it displays its score on another scenario. I finished Electric Fields, but it displayed on Crazy Castle.

**Comment by IntelOrca** [comment] 2015-02-22 18:24
I have pushed another fix attempt, let me know how it goes.

**Comment by IntelOrca** [comment] 2015-02-25 17:55
Anyone?

**Comment by runelaenen** [comment] 2015-02-25 18:01
It seemed to work when I played yesterday.

**Comment by Gymnasiast** [comment] 2015-02-25 18:31
It seems to work for me now. (I'm sorry I didn't comment, I thought you were asking runelaenen specifically.)

**Closed** 2015-02-25 19:06 UTC
Labels: bug
