### ISSUE TITLE
Guest messages ocassionally duplicate the first letter of their name

### ISSUE THREAD

**Issue by rctdude2** [IntelOrca/OpenRCT2#1104] opened 2015-05-19 21:08 UTC
Only seems to happen with guest messages.
![duplicatedletter](https://cloud.githubusercontent.com/assets/8041567/7714017/7ed9c0e0-fe49-11e4-879f-dc7b10efc6cb.png)

**Comment by duncanspumpkin** [comment] 2015-05-19 21:09
Duplicate of #1052

**Closed** 2015-05-19 21:34 UTC
Labels: duplicate
