### ISSUE TITLE
Scenery glitch while building 'Junior Roller Coaster - Crazy Caterpillar'

### ISSUE THREAD

**Issue by danidoedel** [IntelOrca/OpenRCT2#1165] opened 2015-05-29 18:20 UTC
Made a quick video to show what's happening:
https://youtu.be/OxpckpvaaiA

Is it just me or can anybody confirm?

**Comment by Gymnasiast** [comment] 2015-05-29 18:41
It's not just you. I had the issue as well.
I also think it might be related to #259, as both are caused by improperly removing ghost scenery.

**Comment by danidoedel** [comment] 2015-05-29 18:51
Ah ok, I see. Thanks for the reply!

**Comment by IntelOrca** [comment] 2015-05-29 19:01
I have seen this happen quite a lot recently, I think its a bit more severe than #259.

**Comment by Gymnasiast** [comment] 2015-05-29 19:09
Yeah, I tried #259 out recently actually, and the results were worse than in that video, and very similar to the video in this Issue. But they seem to have similarities, since both are not removing ghost scenery properly. That's why I mentioned it. :)

**Comment by IntelOrca** [comment] 2015-05-29 19:12
Yeah that's fine, its just a bit more critical as the effect is much worse in OpenRCT2. Fixing this could indeed lead to the reason behind #259.

**Comment by zsilencer** [comment] 2015-05-29 23:39
this appears to fix it let me know if there are any other issues

**Comment by IntelOrca** [comment] 2015-05-30 01:14
@zsilencer This fixes it for me!!!

**Comment by zsilencer** [comment] 2015-05-30 03:49
ok sweet i will do pr

**Comment by Gymnasiast** [comment] 2015-05-30 12:14
Fixed now, this can be closed.

**Closed** 2015-05-30 12:14 UTC
Labels: bug
