### ISSUE TITLE
Crocodile Ride Car Bug

### ISSUE THREAD

**Issue by pGore33p** [IntelOrca/OpenRCT2#739] opened 2015-02-03 18:23 UTC
I found out that it would be nice if the bug could be fixed. It bugs me so much...
Whenever I construct a Crocodile Ride (log flume type of trains) with 2 stations and a continuous circuit mode it just gives me 5 or less trains (and yes, two of them have the longest stations possible!)... I can't change it on the trainers because 8cars don't work and son of beast needs a "patch", so I really have no idea if I am doing that wrong or so...

Thanks for reading.
Will.

**Comment by duncanspumpkin** [comment] 2015-02-03 18:47
Provide a save and I will see what I can do. Might be able to hack together a little cheat or make a modification and save it and send it back.

**Comment by pGore33p** [comment] 2015-02-03 18:52
Here you go mate ;)

https://www.dropbox.com/s/0xarifgy58kczb4/Fun%20Land2.SV6?dl=0

**Comment by duncanspumpkin** [comment] 2015-02-03 19:49
Can you provide the save with all of the object files. I was going to hunt them all down but I'm missing about 20.

**Comment by pGore33p** [comment] 2015-02-03 19:55
OK so I removed my custom dumb stuff (note: you need time twister) and... here you have it: 
https://www.dropbox.com/s/kgh7cdcjuzr3dwe/Unnamed%20park.SV6?dl=0

**Comment by duncanspumpkin** [comment] 2015-02-03 20:16
I tried a few different ways to force the number of vehicles and it doesn't look like it is possible right now. Once GAME_COMMAND_9 has been reversed (and all its related functions) then we might know how to modify it.

**Comment by pGore33p** [comment] 2015-02-04 08:09
Hmm... ok.
This was just a test to show you that it has 5 trains. The FunLand2.sv6 need this object files:
Rides and Paths from Buggy's RCT2 Depot
A Strange Footpath (Downloadable here: https://www.dropbox.com/s/aqv0mft26rqgwf7/STRANGE.DAT?dl=0 )
UCES (user created expansion set)
Time Twister, Wacky Worlds
RCT2 (obviously -'.-)

**Comment by Gymnasiast** [comment] 2015-02-04 10:00
This bug is in vanilla RCT2 Wacky Worlds. Open any Australasian scenario in RCT2WW and build a Crocodile Ride. It will never allow more than 5 boats, even when the station could easily accommodate more.

**Comment by pGore33p** [comment] 2015-02-04 10:07
Yup you are right, but I think it should be edited on something... have you tried different Wacky Worlds rides?

**Comment by Gymnasiast** [comment] 2015-02-04 14:54
I don't know what you try to say.
I have played RCT2 with Wacky Worlds for years. This bug has always been present in the Crocodile ride. The OpenRCT2 will probably eventually be able to fix it, but since it was not _introduced_ by OpenRCT2, that might take a while.

By the way, 8 cars per trainer and Son of Beast don't work with OpenRCT2, and never will. They only work with unmodified versions of RCT2 (including WW and TT). Some of their functions have been implemented in OpenRCT2, by the way, with probably more to follow.

**Comment by pGore33p** [comment] 2015-02-04 14:59
Umm i am trying to say if some different ride has small ammount on trains as well. I am playing it on vanilla and I don't think I will touch OpenRCT2. But yeah, I have been playing RCT2 for years too and created over 1000 roller coasters (which some of them are scrapped). I mean: Log Flume is fine, but Crocodile Ride isn't. As far of my knowledge goes, I had a ride modifier that can modify rides and save them (yes it has max. trains and cars and all that) but I lost it on my old computer. Since there are so many broken links with 404, I just can't find it. That's why I am asking here because the guests have dumb questions about why they are in the queve line so long? And yes that park is themed... thanks for this occurence.
Will.

**Comment by duncanspumpkin** [comment] 2015-02-04 16:02
Log flumes appear to have different max values even though it is very similar to the croc ride. There is probably a memory address that can be modified that would allow an increase in the number of trains but at this point it would take too long to work it out. If you are still super desperate for it I could reverse a bit of 8 cars trainer and see how it is modifying the number of trains.

**Comment by Gymnasiast** [comment] 2015-02-04 16:32
I think the Crocodile ride only allowing 5 boats is a bug, but one that probably needs fixing on the ride itself. By the way, I don't think 8 cars allows changing the numbers of boats/trains beyond the normal limits. It does have the functions '8 cars per train', which, as the name implies, allows more cars per train.

**Comment by pGore33p** [comment] 2015-02-04 16:35
@duncanspumpkin That's what I am talking about. Yeah, I just need to speed the queve line. The quests complain so much. Just fix that please, I beg you
@Gymnasiast Yes it's a bug, and yes it allows up to normal limits but the program itself is broken and nothing is working.

**Comment by IntelOrca** [comment] 2015-02-04 17:14
So is it just that the object file for this crocodile has a low car limit? Surely its easy enough to modify the value in the ride structure while the ride is closed and then open it...

**Comment by pGore33p** [comment] 2015-02-04 17:16
What do you mean by "croc ride has a low car limit"? It's a bug, chris sawyer just did a mistake in the object file while making the ride. That problem is easily fixed (... I think)

**Comment by IntelOrca** [comment] 2015-02-04 17:19
If it is related the object file, then it is not a bug with OpenRCT2. Ignoring what the limit is in the object file would be a hack enhancement.

**Comment by pGore33p** [comment] 2015-02-04 17:21
@IntelOrca Yes but at the moment I won't touch OpenRCT2... because of the damn issue...

**Comment by IntelOrca** [comment] 2015-02-04 17:23
The issue that isn't related to OpenRCT2?

**Comment by pGore33p** [comment] 2015-02-04 17:27
@IntelOrca No I mean the "Cannot open the damn exe" issue. It is related to OpenRCT but this isn't, I am just saying that it would be nice if this would be fixed in OpenRCT2.

**Comment by IntelOrca** [comment] 2015-02-04 17:30
So you are saying that:
The crocodile issue is not related to OpenRCT2.
You not being able to run the game is related and it would be nice if that was fixed?

**Comment by pGore33p** [comment] 2015-02-04 17:32
@IntelOrca  Yes the crocodile issue is not related to OpenRCT2, but it would be good if it would be FIXED IN THE DAMN OPENRCT2... and I am also saying that the "cannot open the damn exe" is the reason I can't run OpenRCT2, read that article again. This is what I mean.

**Comment by IntelOrca** [comment] 2015-02-04 17:50
@pGore33p I have just committed a new version with more diagnostic log information. Please can you try it using command prompt and the verbose flag again and reply with your results to #702.

As for this crocodile issue, it it is unrelated to OpenRCT2 - there is therefore nothing to be fixed. The object file does not come with OpenRCT2 either, therefore I'd advise you find a way or someone that can modify the crocodile object file for you to increase the limit. Or modify your saved game to manually increase the number of cars for a particular ride. At some point we will allow the limit to be bypassed via some hack option. Thus I am closing this issue.

**Closed by IntelOrca** 2015-02-04 17:50 UTC

**Comment by Gymnasiast** [comment] 2017-06-23 15:32
I have fixed this. The problem is that the Crocodile Ride incorrectly sets a property normally reserved for flat rides. It will now behave like a regular Log Flume.
