### ISSUE TITLE
Water tool cursor outside map causes crash

### ISSUE THREAD

**Issue by oli414** [IntelOrca/OpenRCT2#1273] opened 2015-06-09 11:31 UTC
To recreate the crash:
- Open the Scenario editor.
- Go to the landscape editor.
- Select the water tool.
- Set the size to 8 (Happens with lower sizes too but I got the most "luck" with 8).
- Move your curser outside of the map (Negative side).
- Congratulations, Openrct2.exe has stopped working.

**Comment by kevjoe** [comment] 2015-06-09 11:34
I can confirm that this happens to me too when I try to fix it. It happens for me when I'm at the north-western border of the map.

**Comment by duncanspumpkin** [comment] 2015-06-09 11:35
water tool at present does not handle map elements outside of range. https://github.com/IntelOrca/OpenRCT2/blob/develop/src/world/map.c#L1635-L1642 and https://github.com/IntelOrca/OpenRCT2/blob/develop/src/world/map.c#L1648-L1670 (plus the resepective lower) requires a default for when the map_element is null.

**Comment by duncanspumpkin** [comment] 2015-06-09 11:54
Since this is probably the same issue I'm also copying in @Gymnasiast 
>I get the footpath freeze also in saved games where the edges belong to the park, where removing it did work in vanilla RCT2. It just seems that it only happens on certain edges.
>I think it freezes in viewport_interaction_remove_footpath(), which is called when right clicking a path.

**Comment by kevjoe** [comment] 2015-06-09 13:57
I've tested it, and it doesn't crash anymore but it does print out a lot of errors in the console. 
Adding the error for reference: ERROR[..\src\world\map.c:130 (map_get_first_element_at)]: Trying to access element outside of range.

The error only gets printed on the top of the map, not on the bottom (if you can see the earth, it doesn't print).

I didn't get any crashes though, so I think it's fixed!

**Comment by oli414** [comment] 2015-06-09 14:09
Yeah, I made a fix 2 hours ago https://github.com/IntelOrca/OpenRCT2/pull/1274 someone should take a look at those error messages. Might need to make sure that (map_get_first_element_at) just won't be called if it's outside of the map instead of checking if (map_get_first_element_at) returned anything usefull.

**Comment by IntelOrca** [comment] 2015-06-10 13:51
I am just about to push a fix for this which will also allow you raise or lower the land even if your selection is off the edge of the map.

**Closed** 2015-06-10 14:42 UTC
