### ISSUE TITLE
'whizzed' images

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#1070] opened 2015-05-15 19:42 UTC
Image says more than a 1000 words I guess...
![image](https://cloud.githubusercontent.com/assets/3930922/7660539/3bbde620-fb4b-11e4-8fa8-eef7a047892b.png)

**Comment by runelaenen** [comment] 2015-05-15 19:45
Also, I see this now. When you click them, you get this: 
![image](https://cloud.githubusercontent.com/assets/3930922/7660581/9b864462-fb4b-11e4-9e41-b126d1c03538.png)
And also a thought: shouldn't these (coffee shop, lemonade stand, drink stand and iced tea stand) only appear later in the list instead of first?

**Comment by Gymnasiast** [comment] 2015-05-15 19:57
I had the exact same problem. But only once. I also had the Hot Chocolate Stall show up as an alternative train for the looping roller coaster. Closing and reopening OpenRCT2 made it disappear.

**Comment by PFCKrutonium** [comment] 2015-05-16 07:05
Interestingly enough, that track took on the colors of the Lemonade Stand XD

**Comment by thegreatpl** [comment] 2015-05-17 02:15
I got Roast Sausage, Sea Food, Sub Sandwich and Wonton Soup. None of which I had built before these alternatives appeared in the build list. They do say the cost of the looping rollercoaster when you highlight it. Perhaps something to do with not finding a ride so defaulting to looping rollercoaster?

**Comment by thegreatpl** [comment] 2015-05-17 03:48
Interestingly, when I loaded an autosave after an accident with the console screen (clicked close instead of minimize. After having seen a list of error messages that autosave had been failing for a while), the 4 rollercoaster food stalls were still there.

**Comment by thegreatpl** [comment] 2015-05-17 21:11
Having reloaded the above from an actual save, the 4 whizzed food stalls were still there. After having built a few Balloon and Souvenir stalls, the same four as above returned.

**Comment by duncanspumpkin** [comment] 2015-05-20 20:02
Does anyone have any saves that reliably reproduce this?

**Comment by Gymnasiast** [comment] 2015-05-24 10:53
I have found steps to get the game into this state reliably!

1. Open 'Build your open Six Flags Park'
2. Open the in-game console
3. Execute `open object_selection`
4. Go to the Scenery groups tab.
5. Unselect 'Creepy theming', select 'Urban theming'
6. Open the new ride tab. The whizzed food stalls are now there.

It seems the memory gets corrupted. It might even be related to #1119 and #1084 (both likely the result of memory corruption).

**Comment by runelaenen** [comment] 2015-05-24 11:07
I can confirm that the steps @Gymnasiast posted work to get bad images.

**Comment by trigger-death** [comment] 2015-05-24 14:56
It's actually simpler than that, just opening and closing the object_selection window will trigger this. This is most likely since closing the window will automatically research everything (due to not know what was selected beforehand).

The culprits are the Ice Tea and Lemonade stall. And if you have "Show all vehicles sharing track type" selected. It turns out these are somehow linked to the LIM Launched coaster.

**Comment by duncanspumpkin** [comment] 2015-05-24 15:10
Looks to me like the research functions are breaking. I'm looking at the ride entry numbers and they are too high. I think something is failing to mark an entry as free.

**Comment by Gymnasiast** [comment] 2015-05-26 12:40
Fixed, so this can be closed.

**Closed** 2015-05-26 20:07 UTC
Labels: bug
