### ISSUE TITLE
Add pixel doubling

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#1015] opened 2015-04-13 18:27 UTC
This has been posted on my forums: https://openrct.net/forum/topic/8/Add+pixel+doubling+like+in+openRA

The stuff is so tiny, this would be great! Add pixel doubling like on OpenRA.
http://www.openra.net/

**Comment by zsilencer** [comment] 2015-04-13 23:02
duplicate of #775

**Closed** 2015-04-28 13:56 UTC
Labels: duplicate
