### ISSUE TITLE
Different languages during object selection in scenario editor

### ISSUE THREAD

**Issue by Jak81** [IntelOrca/OpenRCT2#1375] opened 2015-06-17 14:53 UTC
Version: OpenRCT2-0.0.2-pre-release-b814
I am using the English GoG-Version of RCT2 and my OS is Win 7 Pro in German.
Game language is set to English (UK)

The ride names appear in German and all other texts in English at the object selection screen in the scenario editor. Only in this selection they appear in German. Later on the invention screen they are in English again. And when playing the game they are all in English.

I assume in this step is somewhere a query on the system language. But only there. :/

And here a screenshot of the issue:
![scr1](https://cloud.githubusercontent.com/assets/9069551/8209823/69fc9a8a-150f-11e5-830d-dd01c3ffd4ba.png)

Keep up the good work!

**Comment by AaronVanGeffen** [comment] 2015-06-17 15:00
This occurs when changing the language after the object cache has been built. If you delete the plugin.dat file from the OpenRCT2 dir in your documents directory, the cache will be rebuilt on the next launch, with the right labels.

**Comment by duncanspumpkin** [comment] 2015-06-17 15:02
This is a known issue there is already a an issue number assigned. It boils down to I can fix the display issue but then it wont be sorted. I can sort it but it will kill lots of time. I can solve all of these when we come up with a new object list cache when the game is completely implemented.

**Comment by Gymnasiast** [comment] 2015-06-17 15:05
Duplicate of #1004.

**Comment by Jak81** [comment] 2015-06-17 16:16
Thanks, that solved it for me. And sorry, but didn't saw that issue 1004, while searching for this problem.

**Closed** 2015-06-17 16:19 UTC
Labels: duplicate

**Comment by Gymnasiast** [comment] 2015-06-17 17:09
Don't worry. It's better to have two reports than none. I posted my comment to keep the issues list clean. :-)

**Comment by IntelOrca** [comment] 2015-06-17 17:21
I will rename #1004 to a better name.
